// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLToX8XejYLOQUI9S6PXx7K4x6EkavnU',
    appId: '1:806973263338:web:9be5637ce8a84ac1a2b693',
    messagingSenderId: '806973263338',
    projectId: 'testapp-da3a3',
    authDomain: 'testapp-da3a3.firebaseapp.com',
    storageBucket: 'testapp-da3a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPOpV-Y4TxynRGICWTB7n42Qu3VerFTCo',
    appId: '1:806973263338:android:e7ca90387114fb1ea2b693',
    messagingSenderId: '806973263338',
    projectId: 'testapp-da3a3',
    storageBucket: 'testapp-da3a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0hXwgAUFqsqVAnzTmhAG0pXgyRb6YRI',
    appId: '1:806973263338:ios:a989bed081afc04ea2b693',
    messagingSenderId: '806973263338',
    projectId: 'testapp-da3a3',
    storageBucket: 'testapp-da3a3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd0hXwgAUFqsqVAnzTmhAG0pXgyRb6YRI',
    appId: '1:806973263338:ios:71c1b4b2963172c8a2b693',
    messagingSenderId: '806973263338',
    projectId: 'testapp-da3a3',
    storageBucket: 'testapp-da3a3.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
